name: Terraform Deploy

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Terraform inside container
        run: |
          docker run --rm \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
             -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
             -v ${{ github.workspace }}:/app \
             formycore/aws-terraform:latest \
             bash -c "terraform init && terraform destroy"           


      # - name: Run Terraform inside container
      #   run: |
      #     docker run --rm \
      #       -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
      #       -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
      #       -v ${{ github.workspace }}:/app \
      #       formycore/aws-terraform:latest \
      #       bash -c "terraform init && terraform apply -auto-approve"
